### ISSUE TITLE
Error when trying to start a Worker Thread

### ISSUE THREAD

**Issue by dbas-dn** [royaltm/node-murmurhash-native#30]
```
Error: Module did not self-register: '/Users/dbas/Work/NORC-DNOR/node_modules/.pnpm/murmurhash-native@3.5.0/node_modules/murmurhash-native/lib/Release/murmurhash.node'.
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/dbas/Work/NORC-DNOR/node_modules/.pnpm/murmurhash-native@3.5.0/node_modules/murmurhash-native/index.js:6:18)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/Users/dbas/Work/NORC-DNOR/node_modules/.pnpm/@asyncapi+generator@1.10.9_@swc+core@1.3.99_@types+node@18.7.23_bluebird@3.7.2/node_modules/@asyncapi/generator/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Array.Object.defineProperty.value (webpack:///external commonjs "murmurhash-native":1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Array.<anonymous> (webpack:///../../../libs/dnor/shared/backend-utils/src/lib/hash/hash.ts:1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Array.Object.defineProperty.value (webpack:///../../../libs/dnor/shared/backend-utils/src/lib/hash/index.ts:1:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Array.Object.defineProperty.value (webpack:///../../../libs/dnor/shared/backend-utils/src/index.ts:5:1)
    at __webpack_require__ (webpack:///webpack/bootstrap:19:1)
    at Array.<anonymous> (webpack:///../../../libs/dnor/shared/logger/src/lib/logger.ts:7:1)
```

**Comment by royaltm** [comment]
https://stackoverflow.com/questions/28486891/uncaught-error-module-did-not-self-register
